`OvRendering` Rework: Better Rendering capabilities, less redundancy, and code clean-up
adriengivry/Overload pull request #277
Opened 2023-11-26 18:42 UTC by adriengivry

# Description
Initiative to rework `OvRendering` to improve its modularity and prepare the field for upcoming work (such as shadow casting).

This work includes:
* Partially moving `Material` from `OvCore` to `OvRendering` (The serialization part of material remains in `OvCore` for now)
* Moved driver-specific features from `Renderer` to `Driver`
* Improved `StateMask` for materials (take up less memory)
* Renderer functionalities split into "extensions" called "render features"
* Added a render pass system (custom drawing-logic executed in a per-determined order)
* Implemented renderer for scene rendering: `SceneRenderer` (ECS-specific)
* Simplified renderer usage to avoid redundant code between `OvGame`, `OvEditor` and `OvCore`.
* Added support for multiple FBOs
* Adding entities alongside the `Light` entity, such as `Camera` (moved from `LowRenderer`, and `Drawable`, which represent an entity that can be visually drawn).
* Added `PipelineState`, which is an 8 bytes struct that contains information about the graphics context state. Rendering functions pass instances of `PipelineState` to each other by copy, allowing for hierarchical pipeline state updates, i.e. each scope can modify the pipeline state without affecting the level above. Lowest level functions (driver-level) are responsible for requesting the graphics backend to update its internal state. The driver also ensure that no unnecessary state change is performed (this is done by keeping track of the current state of the context, and comparing state change requests with the current state).
* On-going initiative to hide the graphics backend implementation to the rest of the engine. The `HAL` namespace with a `GraphicsAPI` class has been added. This doesn't cover resources such a buffers, textures, and shaders, which individually hold graphics API-specific code (this code should be moved to the HAL in the future).
* Added support for orbit and focus camera actions in Asset View
* Overall rendering code cleanup

# Related Issues
* Fixes https://github.com/adriengivry/Overload/issues/106 (full)
* Related to https://github.com/adriengivry/Overload/issues/59 (partial)
* Related to https://github.com/adriengivry/Overload/issues/148 (partial)
* Related to https://github.com/adriengivry/Overload/issues/250 (partial)
* Related to https://github.com/adriengivry/Overload/issues/221 (partial)

# Screenshots
_Renderer updated architecture_
![Overload-Better-Renderer](https://github.com/adriengivry/Overload/assets/33324216/e0fc8adb-6e28-4655-9396-b9a2c02726a1)

2024-03-15 23:32 UTC, maxbrundev approved these changes

2024-03-18 21:50 UTC, litelawliet requested changes
There is a visual issue when selecting an object having children (with a mesh to render), all segments of all visible triangles are highlighted:
![image](https://github.com/adriengivry/Overload/assets/17803939/61f1b9af-77ca-4261-a522-9f6a2d9fb5f4)

2024-03-18 21:57 UTC, adriengivry commented
> There is a visual issue when selecting an object having children (with a mesh to render), all segments of all visible triangles are highlighted: ![image](https://private-user-images.githubusercontent.com/17803939/313845587-61f1b9af-77ca-4261-a522-9f6a2d9fb5f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTkwMDksIm5iZiI6MTcxMDc5ODcwOSwicGF0aCI6Ii8xNzgwMzkzOS8zMTM4NDU1ODctNjFmMWI5YWYtNzdjYS00MjYxLWE1MjItOWY2YTJkOWZiNWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDIxNTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYWFiY2Q4MDVlZmZiZTFiNzEzZDZhNTkzODMwNzRjYTQ4ZTA2N2RkMmE5NTBlNDYwYjdmOWM4YzE0YjUyYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.II_Dd_GPFOflxCBDs77QoGEKWWpsUw2jmAm2sq42buo)

Fixed ✅

2024-03-18 23:47 UTC, litelawliet approved these changes

2024-03-19 00:18 UTC, merged